services:
  - type: web
    name: easiway-tracker
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    plan: free
    envVars:
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: ServiceAccountKey.json
